### PR TITLE
Signature flutter3

### PR DESCRIPTION
**Pull request by yurtemre7**
Hey,

I have made major improvements to the example project by updating everything to flutter 3 and making the project better then before by splitting widgets and better ui for simple widget tests.

I have also made a discovery of a bad hard-code in the signature.dart file of the package.
The `toPngBytes` method would always make the image 500x400 which is not wanted. Now user can specify a desired height and width, which is still validated in `toImage` to not be less then the original height and width.

If something is unclear, feel free to contact me via [Telegram](https://t.me/emredev) or [E-Mail](mailto:emreyurtseven18@gmail.com).
We can go through all the changes and I hope I can make a good contribution to this package because I personally use it for my work.

### CODE REVIEW

**Review by MartinHlavna — COMMENTED** [review]
I agree with some of the changes, but why Kotlin though? Since this is example and there is even no native code in there it seems to be redundant.

**Review by MartinHlavna — COMMENTED** [review]
Moving ios example from Objective C to swift is the same thing, alas I can see the benefit of having one file instead of header and implementation.

**Comment by MartinHlavna** [comment]
Other changes looks good to me.

**Comment by MartinHlavna** [comment]
I have merged branches manually. I have cherry picked everything but the kotlin migration and also left old package namespace (We are maintaining multiple packages and have all of them on com.example would cause them to overwrite examples which is not something we want). 

I am open about discussion on kotlin but since there is no native code I see little reason for that change. Thanks for the test, it is great addition and will contribute to providing more stable builds. 

Keep up the good work. Thanks!

**Comment by yurtemre7** [comment]
Alright! Thank you!

**Pull request closed without merging**
