### PR TITLE
fixed drawing outside of boundaries

### PR DESCRIPTION
**Pull request by madsane29**

### CODE REVIEW

**Review by MartinHlavna — APPROVED** [review]
Thanks

**Comment by Bungeefan** [comment]
It seems like this change also made it impossible to update the width and height of the widget after the first build call.
What was the reasoning behind putting the widget variables in the initState method?

**Comment by madsane29** [comment]
To be honest I never thought about someone gonna change the size of it dynamically. DId you try it with using setstate?

**Comment by Bungeefan** [comment]
No, I am just providing "new" sizes in my build method.
Then different question, any reason for keeping it in the init State?

**Pull request merged**
