### PR TITLE
Moved boundaries calculation back into build

### LINKED ISSUE #85: Signature ignores new size
If you give a signature widget different sizes throughout the lifecycle of your own stateful widget, the signature pad will ignore those bounds as only the initial bounds are used for paintchecks. The max size of the canvas is only evaluated in the initState function of the signature widget.

### PR DESCRIPTION
**Pull request by Bungeefan**
This fixes the fixed size bug introduced with https://github.com/4Q-s-r-o/signature/pull/62 without reverting their bug fix.

Fixes #85.

### CODE REVIEW

**Comment by MartinHlavna** [comment]
I am curious: 

What is your use case? When do you need to change boundaries dynamically? I think the landscape/portrait should be handled automatically, since most of the parent widgets gets updated anyway. I will test it today though.

**Comment by MartinHlavna** [comment]
Landscape / portrait switch works in example.

**Comment by Bungeefan** [comment]
Thanks for looking into this!
We are working on a generic ui framework which dynamically receives screens via a server.
Therefore, we have a dynamic layout which can change after the initial build.

Project: https://github.com/sibvisions/flutter_jvx

**Comment by MartinHlavna** [comment]
I see. But still it is not necessary to update it in every build. I would rather implement didUpdateWidget  - which should be called in your case and update state values. Can you test it with your use case please? 

If that works for you I will merge updated PR.

**Comment by Bungeefan** [comment]
You are right, I moved it into didUpdateWidget, works fine!

**Comment by Bungeefan** [comment]
@MartinHlavna Any updates for this?

**Comment by MartinHlavna** [comment]
We are currently upgrading to latest flutter, so I hope we can find time for this soon.

**Review by MartinHlavna — APPROVED** [review]

**Comment by Bungeefan** [comment]
@MartinHlavna Thanks for approving, I rebased my fork, so you should be able to merge this without any problems.

**Pull request merged**
